ignore:
  - "examples/"
  - "test/"

parsers:
  gcov:
    branch_detection:
      conditional: no
      loop: yes
      method: no
      macro: no
  
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
        branches: null

    patch:
      default:
        target: auto
        branches: null

    changes: false
